### ISSUE TITLE
Repair tools

### ISSUE THREAD

**Issue by tdurieux** [program-repair/RepairThemAll#1]
1. ACS: https://github.com/Adobee/ACS
2. ARJA: https://github.com/yyxhdy/arja
3. CapGen: https://github.com/justinwm/CapGen
4. JAID: https://bitbucket.org/maxpei/jaid/wiki/Home
5. HistoricalFix: https://github.com/xuanbachle/bugfixes
6. LSRepair: https://github.com/AutoProRepair/LSRepair
7. ssFix: https://github.com/qixin5/ssFix/
8. SketchFix: https://github.com/SketchFix/SketchFix
9. S3: https://xuanbachle.github.io/semanticsrepair/
10. GenProg4Java: https://github.com/squaresLab/genprog4java
11. SimFix: https://github.com/xgdsmileboy/SimFix/
12. VFix: https://github.com/vfix-npe/VFix
13. sharpFix: https://github.com/sharpFix18/sharpFix
14. kGenProg: https://github.com/kusumotolab/kGenProg

**Comment by ruimaranhao** [comment]
Created a wiki page with this information. Closing this issue.
