### ISSUE TITLE
Where can I find the data produced by the docker image?

### ISSUE THREAD

**Issue by jose** [program-repair/RepairThemAll#18]
Hi @tdurieux,

I am using the docker image (id fbbb430881e3) you kindly provided to run Nopol on Math-76 from the Defects4J benchmark:
```
$ mkdir -p /tmp/repairthemall/attempt_9_7_2019
$ docker run -it --rm -v /tmp/repairthemall/attempt_9_7_2019:/results tdurieux/repairthemall Nopol -b Defects4J -i Math_76
1 Running, 0 Waiting, 0/1 Finished, 0 Patched, 0 Error
Running:
1. Nopol Defects4J_Math_76 0:03:13
Patched bug:



1 Finished, 1 Patched, 0 Error

Check the results and logs in /results/
```
but I can't find the results/log files. I noticed the message `Check the results and logs in /results/` but where is that `/results/`? I was expecting to find the results/log files in `/tmp/repairthemall/attempt_9_7_2019`, otherwise why would I need to provide a `<absolute_path_to_store_results>` as suggested in [here](https://github.com/program-repair/RepairThemAll/blob/master/INSTALL.md#execute-1)... 😅

My system:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132

$ docker --version
Docker version 18.09.7, build 2d0083d
```

--
Best,
Jose

**Comment by tdurieux** [comment]
`Check the results and logs in /results/ but where is that /results/?`
This message is only valid when you run it locally. The results are in `tmp/repairthemall/attempt_9_7_2019`.

**Comment by jose** [comment]
That's what I thought but there is not file in `/tmp/repairthemall/attempt_9_7_2019`.

**Comment by tdurieux** [comment]
That is strange :/
Did the folder `/tmp/repairthemall/attempt_9_7_2019` exist, when you started the execution?

**Comment by jose** [comment]
Yep. As you can see in my first message, I create the folder `/tmp/repairthemall/attempt_9_7_2019` before executing the docker command.

**Comment by tdurieux** [comment]
It is really strange, I tried again the docker image and the output is correctly created.
(my command line: `docker run -it --rm -v /tmp/Chart_1_buggy:/results tdurieux/repairthemall Nopol -b Defects4J -i Math_76`)
Are you sure that `/tmp/repairthemall/attempt_9_7_2019/Defects4J/Math/76/Nopol/7/repair.log` does not exist? 

I have the same os version and a slightly older docker version.

**Comment by jose** [comment]
> It is really strange

Indeed.

> I tried again the docker image and the output is correctly created (but no patch is generated).

Are you using docker image id fbbb430881e3?

> Are you sure that /tmp/repairthemall/attempt_9_7_2019/Defects4J/Math/76/Nopol/7/repair.log does not exist?

```
$ cat /tmp/repairthemall/attempt_9_7_2019/Defects4J/Math/76/Nopol/7/repair.log
cat: /tmp/repairthemall/attempt_9_7_2019/Defects4J/Math/76/Nopol/7/repair.log: No such file or directory
```

> I have the same os version and a slightly older docker version.

Any chance you could try to run the command on the same docker version I am using? I know nothing about docker so I followed [this guide](https://medium.com/@yutafujii_59175/a-complete-one-by-one-guide-to-install-docker-on-your-mac-os-using-homebrew-e818eb4cfc3) to install it on my machine. Could my installation be, somehow, broken?

----

I've just tried a couple other bugs and `/tmp/repairthemall/attempt_9_7_2019` is still empty. Is there any log I can access by sshing the docker image? Or maybe any other parameter I could use to make the execution more verbose? So that we could try to understand what's going on...

**Comment by tdurieux** [comment]
> Are you using docker image id fbbb430881e3?
Yes, I do use the same image

I tried to use the same folder name and the exact same command line and it is working :/ 

Could you check the permission of the folder `/tmp/repairthemall/attempt_9_7_2019`?

> Any chance you could try to run the command on the same docker version I am using? 
Docker said that `You’re up-to-date!` :/

>  know nothing about docker so I followed this guide to install it on my machine.
Normally, you have nothing to do to be able to use this Docker image.

>  Or maybe any other parameter I could use to make the execution more verbose?
The tool does not support a verbose mode for the moment, I will try to do it in the following days.

**Comment by jose** [comment]
> Could you check the permission of the folder `/tmp/repairthemall/attempt_9_7_2019`?

The permissions look ok to me:
```
$ ls -la /tmp/repairthemall/attempt_9_7_2019
total 0
drwxr-xr-x 2 jose wheel 64 Jul  9 17:37 ./
drwxr-xr-x 3 jose wheel 96 Jul  9 17:37 ../
```

Can I ssh the docker image and run stuff locally? If yes, how?

**Comment by tdurieux** [comment]
You can do something like this:
```
docker run -it --entrypoint /bin/bash tdurieux/repairthemall
cd script;
python repair.py Nopol -b Defects4J -i Math_76;
cat /results/Defects4J/Math/76/Nopol/7/repair.log;
```

**Comment by jose** [comment]
Thanks @tdurieux, that did work without any issue.

---

I think I got to the bottom of the problem. It seems that `/tmp` is not mounted by docker (or maybe the VM, I am not sure) and therefore no file could ever be written to that directory. If I change the `-v` option to, for example, my deskop folder, it works just fine:
```
$ docker run -it --rm -v /Users/jose/Desktop:/results tdurieux/repairthemall Nopol -b Defects4J -i Math_76

$ find /Users/jose/Desktop/Defects4J/Math/76/Nopol/7/
/Users/jose/Desktop/Defects4J/Math/76/Nopol/7/
/Users/jose/Desktop/Defects4J/Math/76/Nopol/7/result.json
/Users/jose/Desktop/Defects4J/Math/76/Nopol/7/repair.log
/Users/jose/Desktop/Defects4J/Math/76/Nopol/7/detailed-result.json
```
Although this issue has been around for quite some time, I have not managed to find a proper solution.
- Fev, 2015 -- https://github.com/docker/compose/issues/1039
- Jun, 2016 -- https://stackoverflow.com/questions/37673140/docker-volume-located-in-tmp-on-osx-empty

Did you configure docker or docker-compose or the VM to be able to read/write to `/tmp`? I noticed on VirtualBox that the only 'Shared Folder' of the VM that's running is `/Users`. So, I

1. Stopped docker, `$ docker-machine stop default`
2. Added `/tmp` as a 'Shared Folder' to the VM on VirtualBox with read/write permissions and auto-mount enabled
3. Restarted docker, `$ docker-machine start default`
4. Re-ran the docker command, `docker run -it --rm -v /tmp/repairthemall/attempt_9_7_2019:/results tdurieux/repairthemall Nopol -b Defects4J -i Math_76`. And got the same outcome, no file was written or copy to `/tmp/repairthemall/attempt_9_7_2019`.

I guess I will have to use any directory in `/Users`.

PS: You might want to add a few words about this problem to the docker section in the [README file](https://github.com/program-repair/RepairThemAll/blob/master/INSTALL.md#from-docker), so that others could easily figure out why no file is written to the provided directory.

**Comment by tdurieux** [comment]
Thank you for investigating this.

Here is my configuration of my Docker `File Sharing` settings. I don't remember that I modified it but maybe it is different on your laptop.
<img width="522" alt="Screenshot 2019-07-10 at 22 13 37" src="https://user-images.githubusercontent.com/5577568/61005427-12da6000-a360-11e9-896e-af167137677d.png">

It is a good idea to add view words about this in the usage.

**Comment by jose** [comment]
Ah, I don't think I have that app. Is that 'Docker Desktop for Mac'? Did you install it from [docker hub](https://hub.docker.com/editions/community/docker-ce-desktop-mac)? Or did you use [homebrew](https://brew.sh/) to install it?

**Comment by tdurieux** [comment]
Yes it is 'Docker Desktop for Mac', I installed it from docker hub, I had an issue with homebrew

**Comment by jose** [comment]
Ok, I should have installed the following (which is basically the 'Docker Desktop for Mac')
```
$ brew cask install docker
```
The files are now written to `/tmp`.

Once again, thanks for your help @tdurieux.

**Comment by tdurieux** [comment]
> Once again, thanks for your help @tdurieux.

With pleasure, it is always nice to see that people succeed to use our tool!
