### ISSUE TITLE
Why my init step fails?

### ISSUE THREAD

**Issue by Kaka727** [program-repair/RepairThemAll#3]
Dear authors,
  Thanks for your great work!
  Now I am trying to do some replicate experiments. But my init step fails as following:
![image](https://user-images.githubusercontent.com/33283686/58927931-0e2ff400-8783-11e9-8fc2-1e87fb41e537.png)

  Seems that it could not read from the GitHub repository of bugs.jar. I just don't know why it happens.

**Comment by tdurieux** [comment]
Hello,

That is a strange bug. Can you clone `git clone git@github.com:tdurieux/bugs-dot-jar-dissection.git`?

**Comment by tdurieux** [comment]
or maybe it is related to the public key that is used during the git clone.
However, all the repositories are public.

**Comment by Kaka727** [comment]
I read the README in the bugs.jar repository and execute the commend git clone --recursive https://github.com/tdurieux/bugs-dot-jar-dissection  
and it works well
So I have to manually install the dependencies?

**Comment by tdurieux** [comment]
Normally the init script does exactly the same thing.

I will investigate

On Jun 5, 2019 10:05, Kaka727 <notifications@github.com> wrote:

I read the README in the bugs.jar repository and execute the commend git clone --recursive https://github.com/tdurieux/bugs-dot-jar-dissection
and it works well
So I have to manually install the dependencies?

**Comment by Kaka727** [comment]
Thank you so much!
So after downloading the bugs.jar repository and moving it under the path /benchmark/Bug-dot-jar, what else do I need to do ?

**Comment by tdurieux** [comment]
You should check that all folders in benchmarks contain  files. And if you want to use nopol you will need to compile z3 in libs

On Jun 5, 2019 10:20, Kaka727 <notifications@github.com> wrote:

Thank you so much!
So after downloading the bugs.jar repository and moving it under the path /benchmark/Bug-dot-jar, what else do I need to do ?

**Comment by Kaka727** [comment]
Hi, 
I note that you just updated the init.sh file. So I re-downloaded the repository and re-ran the init file.
This time, it is a build failure.
![image](https://user-images.githubusercontent.com/33283686/58941424-56184080-87ae-11e9-8fe3-b5ed526899be.png)
The detailed information shows that it is a "No goals have been specified for this build" error.
![image](https://user-images.githubusercontent.com/33283686/58941584-ac857f00-87ae-11e9-8782-5e3ac7767b44.png)

Need your help~

**Comment by tdurieux** [comment]
It is probably the version of your maven. Which version do you use?

It is the last line of the unit.sh file that is failing. Can you try the final line by replacing 3.1.1 by 3.0.0.

Best,

Thomas

On Jun 5, 2019 11:26, Kaka727 <notifications@github.com> wrote:

Hi,
I note that you just updated the init.sh file. So I re-downloaded the repository and re-ran the init file.
This time, it is a build failure.
[image]<https://user-images.githubusercontent.com/33283686/58941424-56184080-87ae-11e9-8fe3-b5ed526899be.png>
The detailed information shows that it is a "No goals have been specified for this build" error.
[image]<https://user-images.githubusercontent.com/33283686/58941584-ac857f00-87ae-11e9-8782-5e3ac7767b44.png>

Need your help~

**Comment by Kaka727** [comment]
My maven version is 3.5.2.
I replaced 3.1.1 by both 3.0.0 and 3.5.2. However, neither works.

**Comment by tdurieux** [comment]
Can you try this line: mvn org.apache.maven.plugins:maven-dependency-plugin:3.0.0:get -DremoteRepositories=https://durieux.me/maven-repository/snapshots/ -Dartifact=com.github.tdurieux:project-config-maven-plugin:1.0-SNAPSHOT -U;
?

On 5 Jun 2019, at 11:40, Kaka727 <notifications@github.com<mailto:notifications@github.com>> wrote:


My maven version is 3.5.2.
I replaced 3.1.1 by both 3.0.0 and 3.5.2. However, neither works.

**Comment by Kaka727** [comment]
Well, thanks for your patent answer.
But the new line still does not work.

**Comment by tdurieux** [comment]
Ok :( in this case you can clone and install https://github.com/tdurieux/project-info-maven-plugin

**Comment by martinezmatias** [comment]
Hi @tdurieux 

I had a problem when installing that plugin.
In particular, I had to cloned and install and then It worked.

**Comment by Kaka727** [comment]
@martinezmatias Do you mean you successfully installed the plugin?
I note that the installation commend in the plugin is the same as the commend in the init.sh.
So I still failed.
I'd appreciate it if you could tell me how to install it.

**Comment by martinezmatias** [comment]
For installing the plugin:
git clone https://github.com/tdurieux/project-info-maven-plugin

go to the dir

mvn install

**Comment by Kaka727** [comment]
I tried this way but it still failed.
The same reason as before:
![image](https://user-images.githubusercontent.com/33283686/58949815-e90da680-87bf-11e9-8504-382918215040.png)

**Comment by tdurieux** [comment]
Do you have a proxy installed? Because it seems that you don't succeed to download commun maven plugins

**Comment by Kaka727** [comment]
Just now our group tried to install this framework on another computer.
It still failed for two reasons:

1. permission denied for the remote link to the repository
2. build failure for the maven plugin

Seems that the two reasons do not happen in my environment coincidentally.

**Comment by tdurieux** [comment]
The problem 1. is probably related to the fact we used an ssh+hit link for submodules. You need a registered ssh public key on GitHub.
2. Is unknown. I would not expect this error.

I am on holidays with a limited connection, I will address this issue this weekend.

**Comment by tdurieux** [comment]
@Kaka727 
- which operating system do you use?
- which python version? 
- which java version do you use?

Thanks

**Comment by Kaka727** [comment]
My Ubuntu is 15.10.
Python is 2.7.
For Java，I have both 1.7 and 1.8. I use 1.8 when executing the init commend. 




------------------ Original ------------------

**Comment by tdurieux** [comment]
The error you get when installing project-info-maven-plugin, is due to an error of http protocol, the java version is too old :/.
Can you try to install with: mvn -Dhttps.protocols=TLSv1.2 install -DskipTests

**Comment by Kaka727** [comment]
@tdurieux Thanks! It's amazing. This time it works and now I can run the experiment.

**Comment by Kaka727** [comment]
One more question: how to set the working directory?
Seems that I must set it as the directory to RepairthemAll since the z3 file is only under the libs folder in this path

**Comment by Kaka727** [comment]
Since I find this error when executing Nopol:

java.lang.IllegalArgumentException: File does not exist in: '/home/kaka/Desktop/RepairThemAll/script/../libs/z3/build/z3'
	at xxl.java.library.FileLibrary.fail(FileLibrary.java:129)
	at xxl.java.library.FileLibrary.openFrom(FileLibrary.java:29)
	at xxl.java.library.FileLibrary.ensurePathIsValid(FileLibrary.java:19)
	at fr.inria.lille.commons.synthesis.smt.solver.SolverFactory.<init>(SolverFactory.java:50)
	at fr.inria.lille.commons.synthesis.smt.solver.Z3SolverFactory.<init>(Z3SolverFactory.java:22)
	at fr.inria.lille.commons.synthesis.smt.solver.SolverFactory.setSolver(SolverFactory.java:39)
	at fr.inria.lille.repair.Main.parseArguments(Main.java:172)
	at fr.inria.lille.repair.Main.main(Main.java:66)

**Comment by tdurieux** [comment]
> One more question: how to set the working directory?

Everything can be configured in [`script/config.py`](https://github.com/program-repair/RepairThemAll/blob/master/script/config.py#L7). The process is: copy bug in a unique folder, copy the dependencies, set up the tool, run the tools, copy the results in the results folder, remove the tmp file. I don't think it is really useful to change the working directory.
Maybe you would like to edit the [result folder](https://github.com/program-repair/RepairThemAll/blob/master/script/config.py#L8)

> java.lang.IllegalArgumentException: File does not exist in: 

Did you build z3? If no, you should do (it will take some time):
```bash
cd libs/z3
python scripts/mk_make.py --java
cd build
make
make install
```

I am also finishing a Docker image that includes everything, I still need to finish to build z3 for Docker.

**Comment by Kaka727** [comment]
Ok. Everything goes well now.
Hope to use your docker image as soon as possible.
Thanks a lot.
