### ISSUE TITLE
About GZoltar version

### ISSUE THREAD

**Issue by Ringbo** [program-repair/RepairThemAll#32]
Hi, 
A recent ICSE article (Titled: [On the efficiency of test suite based program repair](https://brucekuiliu.github.io/papers/liu2020efficiency.pdf)) used this framework, but they replaced the fault localization with GZoltar-1.7. 
I'd like to know which version of the original Repairthemall is used. Is it all GZoltar-0.1?
Thanks!
Best.

**Comment by mou23** [comment]
I asked the same question to Thomas Durieux. He replied that Repairthemall uses the default GZoltar that is provided by the different repair tools. 
You can examine the corresponding source code from commit IDs of the tools (provided in the paper) to know the GZoltar version.
Hope it helps.

**Comment by Ringbo** [comment]
> I asked the same question to Thomas Durieux. He replied that Repairthemall uses the default GZoltar that is provided by the different repair tools.
> You can examine the corresponding source code from commit IDs of the tools (provided in the paper) to know the GZoltar version.
> Hope it helps.

I checked it on Astor and Arja system tools. It's seem that them all use GZoltar-0.1.1 as default fault localization tool.
Thanks!
