### ISSUE TITLE
SVN dependency

### ISSUE THREAD

**Issue by alcides** [program-repair/RepairThemAll#37]
I tried to find the usage of SVN in the repo, but couldn't find any. There is a verification step, and that's it.

Can you confirm SVN is really required? Otherwise, it should be removed.

**Comment by tdurieux** [comment]
https://github.com/rjust/defects4j#requirements Defects4j requires SVB apparently.

**Comment by alcides** [comment]
I had SVN 1.7 on the cluster I use and I had to turn off this requirement. I tested some Defects4J bugs, but not all. Feel free to ignore this issue, then. I do not have the time to figure out which bug requires SVN.
