### ISSUE TITLE
The directory of external project does not exist! ?

### ISSUE THREAD

**Issue by Kaka727** [program-repair/RepairThemAll#6]
Hi authors, I met a very strange problem when executing ARJA system.
In the log, it does transport a parameter named externalProjRoot
![image](https://user-images.githubusercontent.com/33283686/59846224-d97e8800-9391-11e9-972a-68ebaf2ba73e.png)

But it ends with an error: The directory of external project does not exist!
![image](https://user-images.githubusercontent.com/33283686/59846264-f1eea280-9391-11e9-9d52-31f7b0ba28cd.png)

I cannot understand. Have you met the same problem?
Thanks

**Comment by tdurieux** [comment]
Hello,

Can you provide us the repair.log file of this execution?

Thanks

**Comment by Kaka727** [comment]
[repair.log](https://github.com/program-repair/RepairThemAll/files/3310277/repair.log)

Here it is.

**Comment by tdurieux** [comment]
Does this folder exist: `/home/kaka/Desktop/RepairThemAll/script/../libs/arja_external`

**Comment by Kaka727** [comment]
Yes, it exists. Now I guess it is related to the jdk version. Does the .jar file of Arja build under jdk 1.7?

**Comment by Kaka727** [comment]
Actually, I modify some source code of ARJA and recreate a jar file for RepairThemAll. 
But just now I find that the jdk version of my file is also 1.7. 
Here is my jar file
[jarfile.zip](https://github.com/program-repair/RepairThemAll/files/3310365/jarfile.zip)

Compared with the original jar file, mine contains some extra files like JavaSE-1.8. My version is 1.7 but why these files exist.
![image](https://user-images.githubusercontent.com/33283686/59849648-d1771600-939a-11e9-9a6b-0bfab10d733a.png)

I think it is the main reason.

**Comment by tdurieux** [comment]
Maybe you used a different revision of arja compared to ours, and the argument changed.
With our version it was `-DexternalProjRoot /home/kaka/Desktop/RepairThemAll/script/../libs/arja_external \` you should check in your revision what is the parameter.

**Comment by Kaka727** [comment]
I find no change about this argument.
What's more, according to ARJA's code, it will create a new file even if we transfer an invalid one.
![image](https://user-images.githubusercontent.com/33283686/59851180-8eb73d00-939e-11e9-939d-9a5f087eeeb8.png)

A very curious problem. Maybe I should ask its author for help~

**Comment by tdurieux** [comment]
Does it work with the original jar?

**Comment by Kaka727** [comment]
Yes. It works.
It does not work for my jar.

**Comment by tdurieux** [comment]
can you try to generate the jar with maven (see attached jar)
[pom.xml.zip](https://github.com/program-repair/RepairThemAll/files/3310505/pom.xml.zip)

**Comment by tdurieux** [comment]
I am sorry I did not realize that I added the parameter to Arja locally. I will create a PR to Arja to support maven compilation and this parameter.
You can find my repo here: https://github.com/tdurieux/arja

**Comment by Kaka727** [comment]
You are welcome. Thanks for your kindly help.
Seems that I can download the maven project from your repo and it will work.
I will have a try soon.

**Comment by Kaka727** [comment]
I'd like to know how to solve these errors.
![image](https://user-images.githubusercontent.com/33283686/59852936-6fbaaa00-93a2-11e9-85b1-c8c83339cb61.png)

I tried Maven project update but it didn't work.

**Comment by Kaka727** [comment]
It works now after I changed my local code according to your pull request.
Thanks~
