### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by martinezmatias** [program-repair/RepairThemAll#9]
Hi Thomas, 
When running the script repair, I got the following error:

Traceback (most recent call last):
  File "script/repair.py", line 5, in <module>
    from core.utils import get_benchmark, parser
  File "/Users/matias/develop/code/RepairThemAll/script/core/utils.py", line 49, in <module>
    import core.repair_tools.CapGen
ImportError: No module named CapGen

Similar to modules, import core.repair_tools.LSRepair and import core.repair_tools.TestInfo.

Did I forget to do something?
Thanks!
Matias

**Comment by tdurieux** [comment]
Sorry, I forget to remove those imports
